# -*- coding: utf-8 -*-
"""preprocess_labels.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16LYyDK16h6NOEF7v1X9EyF5XOhrOukF2
"""


import cv2
import requests
import ndjson
import json
import os


from labelbox import Client
API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbGJ0bWV6aHQ5eW5vMDgxMDFvcTUyc3QxIiwib3JnYW5pemF0aW9uSWQiOiJjbGJ0bWV6ZmI5eW5uMDgxMGduZGk2OXZtIiwiYXBpS2V5SWQiOiJjbGJ1c2w1eW4ydDRlMDgwbDd6dHYyaTFkIiwic2VjcmV0IjoiNDhiMGYxYTI5NzZiMzFmODFhMmQwMjdhMzQ2ZGFhYTgiLCJpYXQiOjE2NzE0NTQwNTMsImV4cCI6MjMwMjYwNjA1M30.byH8m7_7qZZCxO3SHY14JIS_Xer0JPy5i-WH16DJ5jM"
client = Client(api_key=API_KEY)
project = client.get_project('clbtwzgas9u4g070i4kr26byi')

export_url = project.export_labels()

print(export_url)

exports = requests.get(export_url).json()

exports[-1]

annotations_url = exports[0]["Label"]["frames"]
print(annotations_url)

headers = {"Authorization": f"Bearer {API_KEY}"}
annotations = ndjson.loads(requests.get(annotations_url, headers=headers).text)

annotations[-1]